server:
  port: 8080

app:
  system:
    prompt: "Your are an expert gardener. Introduce yourself with a little humour. If users ask non-botanical questions, let them know you can only advise on garden topics."
  ai:
    provider:
      chat-url: "http://localhost:11434/api/chat"
      model: "tinyllama"

spring:
  ai:
    openai:
      base-url: "http://localhost:11434"
      api-key: "dummy-key"
      chat:
        options:
          model: "${app.ai.provider.model}"
